### ISSUE TITLE
[BE] SideDish 데이터베이스 설계 (ERD)

### ISSUE THREAD

**Issue by ku-kim** [Louie-03/sidedish#6]
## 기능 요청사항

- SideDish 웹 애플리케이션에 필요한 DB 설계가 필요합니다.

## 요청 세부사항

- ERD
- Mysql 8.0

**Comment by Louie-03** [comment]
[WIKI](https://github.com/Louie-03/sidedish/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%84%A4%EA%B3%84-(ERD))에 작성한 ERD 문서를 추가했습니다.
